
{
    'name': "TMC Base",
    'summary': 'Main TMC models and functionality',
    'version': '10.0.1.0.0',
    'website': 'https://www.tmcrosario.gob.ar',
    'author': 'Tribunal Municipal de Cuentas - Municipalidad de Rosario',
    'license': 'AGPL-3',
    'sequence': 150,
    'depends': [
        'web_x2many_delete_all',
        'web_hide_db_manager_link',
        'auditlog',
        'web_favicon',
        'base_optional_quick_create',
        'web_export_view',
        'web_listview_range_select',
        'web_sheet_full_width',
        # 'mass_editing',
        'web_tree_many2one_clickable',
        'base_technical_features',
        'web_search_with_and',
        'report_py3o'
    ],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/tmc_menus.xml',
        'views/country_state_views.xml',
        'views/country_state_menus.xml',
        'views/dependence_views.xml',
        'views/dependence_menus.xml',
        'views/dependence_order_views.xml',
        'views/document_views.xml',
        'views/document_menus.xml',
        'views/document_topic_views.xml',
        'views/document_topic_menus.xml',
        'views/document_type_views.xml',
        'views/document_type_menus.xml',
        'views/employee_views.xml',
        'views/employee_menus.xml',
        'views/highlight_views.xml',
        'views/institutional_classifier_views.xml',
        'views/institutional_classifier_menus.xml',
        'views/office_views.xml',
        'report/report_dependence_document_topics.xml'
    ],
    'demo': [],
    'installable': True,
    'application': False,
    'qweb': [],
}
