name: Deployment Pipeline

on:
  push:
    branches:
      - "14.0"

  pull_request:
    branches:
      - "14.0"
    types: [closed]

jobs:
  build:
    name: "Build and Push Docker Image"
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: echo "TAG_NAME=${GITHUB_REF_NAME%%[.0]*}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout Dockerfile source
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.GIT_PRIVATE_REPOSITORY }}
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GIT_AUTH_TOKEN }}
          set-safe-directory: ''
          fetch-depth: 0
      - name: Build and push private Docker image
        uses: docker/build-push-action@v3
        with:
          context: "."
          build-args: GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}
          push: true
          tags: ${{ secrets.DOCKERHUB_NAMESPACE }}/odoo:${{env.TAG_NAME}}

  scan:
    name: "Snyk Security Checks"
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: echo "TAG_NAME=${GITHUB_REF_NAME%%[.0]*}" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull image from private repository
        run: docker pull ${{ secrets.DOCKERHUB_NAMESPACE }}/odoo:${{env.TAG_NAME}}
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ secrets.DOCKERHUB_NAMESPACE }}/odoo:${{env.TAG_NAME}}
          args: --severity-threshold=high

  deploy:
    name: "Deploy to Docker Compose Stack"
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/host.key
          chmod 600 ~/.ssh/host.key
          cat >>~/.ssh/config <<END
          Host host
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/host.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Set environment variables
        run: echo "TAG_NAME=${GITHUB_REF_NAME%%[.0]*}" >> $GITHUB_ENV

      - name: Download Docker Image
        run: ssh host 'docker pull ${{ secrets.DOCKERHUB_NAMESPACE }}/odoo:${{env.TAG_NAME}}'

      - name: Stop Odoo Server
        run: ssh host 'docker compose --file /home/${{ secrets.SSH_USER }}/odoo/compose.yml stop web'

      - name: Start Odoo Server
        run: ssh host 'docker compose --file /home/${{ secrets.SSH_USER }}/odoo/compose.yml up web --force-recreate --scale web=4 --detach'